version: "3.8"

services:
  db:
    image: postgres:16.1
    container_name: "postgres_db"
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    restart: always
    env_file:
      - .env_template

volumes:
  pgdata:

